import { useEditorStore } from './editor-store';

export const useSelectedRackId = () => useEditorStore((state) => state.selectedRackId);
export const useHoveredRackId = () => useEditorStore((state) => state.hoveredRackId);
export const useCanvasZoom = () => useEditorStore((state) => state.zoom);
export const useLayoutDraftState = () => useEditorStore((state) => state.draft);
export const useDraftDirtyState = () => useEditorStore((state) => state.isDraftDirty);
export const useResetDraft = () => useEditorStore((state) => state.resetDraft);
export const useInitializeDraft = () => useEditorStore((state) => state.initializeDraft);
export const useMarkDraftSaved = () => useEditorStore((state) => state.markDraftSaved);
export const useSetSelectedRackId = () => useEditorStore((state) => state.setSelectedRackId);
export const useSetHoveredRackId = () => useEditorStore((state) => state.setHoveredRackId);
export const useSetCanvasZoom = () => useEditorStore((state) => state.setZoom);
export const useUpdateRackPosition = () => useEditorStore((state) => state.updateRackPosition);
export const useRotateRack = () => useEditorStore((state) => state.rotateRack);
export const useUpdateRackGeneral = () => useEditorStore((state) => state.updateRackGeneral);
export const useUpdateFaceConfig = () => useEditorStore((state) => state.updateFaceConfig);
export const useUpdateSectionLength = () => useEditorStore((state) => state.updateSectionLength);
export const useAddSection = () => useEditorStore((state) => state.addSection);
export const useAddLevel = () => useEditorStore((state) => state.addLevel);
export const useSetFaceBMode = () => useEditorStore((state) => state.setFaceBMode);
